config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  root to: 'home#index'

  resources :projects, only: %i[index new create show edit update] do
    resources :project_proposals, only: %i[index update new create show] # shallow nesting breaks form_with on project show page
    post 'close', on: :member
    post 'finish', on: :member
    get 'my_projects', on: :collection
  end

  resources :project_proposals, only: %i[edit update destroy] do
    post 'approve', on: :member
    get 'cancel', on: :member
    get 'rate', on: :member
    get 'reject', on: :member
  end

  resources :professional_profiles, only: %i[new create edit update show]

  resources :feedbacks, only: %i[new create show] do
    get 'received/:user_id', on: :collection, to: 'feedbacks#feedbacks_received', as: :received
  end

  resources :knowledge_fields, only: %i[index new create]

  scope '/admin' do
    get 'manage_records', to: 'admin#manage_records'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :feedbacks, only: %i[index show]
      resources :knowledge_fields, only: %i[index show]
      resources :professional_profiles, only: %i[index show]
      resources :projects, only: %i[index show]
      resources :project_proposals, only: %i[index show]
      resources :users, only: %i[index show]
      get 'managers', to: 'users#managers'
      get 'professionals', to: 'users#professionals'
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  mount Coverband::Reporters::Web.new, at: '/coverage'
  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/models/professional_profile.rb
class ProfessionalProfile < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :knowledge_field
  has_one_attached :profile_photo

  validates :profile_photo, :full_name, :social_name, :description, :professional_qualification,
            :professional_experience, :birth_date, presence: true
  validates :user_id, uniqueness: {
    message: 'já possui um perfil cadastrado'
  }

  validate :birth_date_must_be_in_the_past

  def creator?(user_param)
    user == user_param
  end

  private

  def birth_date_must_be_in_the_past
    errors.add(:birth_date, 'deve estar no passado') if birth_date && birth_date >= Date.current
  end
end

app/controllers/api/v1/professional_profiles_controller.rb
class Api::V1::ProfessionalProfilesController < Api::V1::ApiController
  def index
    @professional_profiles = ProfessionalProfile.all

    return render_not_found if @professional_profiles.nil?

    render status: :ok, json: @professional_profiles
  end

  def show
    @professional_profile = ProfessionalProfile.find(params[:id])

    render status: :ok, json: @professional_profile
  end
end

app/controllers/professional_profiles_controller.rb
class ProfessionalProfilesController < ApplicationController
  before_action :require_professional_login, except: %i[show]
  before_action :professional_must_fill_profile, except: %i[new create show]
  before_action :set_professional_profile, only: %i[edit update show]
  before_action :set_projects, only: %i[show]
  before_action :check_authorization, only: %i[edit update]

  def new
    @professional_profile = ProfessionalProfile.new
  end

  def create
    @professional_profile = ProfessionalProfile.new(professional_profile_params)
    @professional_profile.user = current_user

    if @professional_profile.save
      redirect_to @professional_profile, success: 'Perfil cadastrado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @professional_profile.update(professional_profile_params)
      redirect_to @professional_profile, success: 'Perfil atualizado com sucesso!'
    else
      render :edit
    end
  end

  def show; end

  private

  def professional_profile_params
    params.require(:professional_profile).permit(:profile_photo, :full_name, :social_name, :description, :birth_date,
                                                 :professional_qualification, :professional_experience, :knowledge_field_id)
  end

  def require_professional_login
    return if current_user&.professional? || current_user&.admin?

    sign_out current_user
    redirect_to new_user_session_path, notice: 'Acesso restrito a profissionais autenticados.'
  end

  def set_professional_profile
    @professional_profile = ProfessionalProfile.find(params[:id])
  end

  def check_authorization
    return if @professional_profile.creator?(current_user)

    redirect_to @professional_profile, alert: 'Somente o usuário pode atualizar o próprio perfil.'
  end

  def set_projects
    user = @professional_profile.user
    @projects = Project.joins(project_proposals: :feedbacks).where(project_proposals: { user:
      user }, feedbacks: { feedback_receiver: user }).select('projects.*, feedbacks.score AS score')
  end
end

app/views/professional_profiles/_form.html.erb
<%= form_with model: @professional_profile do |f| %>
  <div class="form-floating mb-3">
    <%= f.text_field :full_name, placeholder: :full_name, class: "form-control" %>
    <%= f.label :full_name %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :social_name, placeholder: :social_name, class: "form-control" %>
    <%= f.label :social_name %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :description, placeholder: :description, class: "form-control" %>
    <%= f.label :description %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :professional_qualification, placeholder: :professional_qualification, class: "form-control" %>
    <%= f.label :professional_qualification %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :professional_experience, placeholder: :professional_experience, class: "form-control" %>
    <%= f.label :professional_experience %>
  </div>
  <div class="form-floating mb-3">
    <%= f.collection_select :knowledge_field_id, KnowledgeField.order(:title), :id, :title, {}, class: "form-select" %>
    <%= f.label :knowledge_field_id, KnowledgeField.model_name.human %>
  </div>
  <div class="form-floating mb-3">
    <%= f.date_field :birth_date, placeholder: :birth_date, class: "form-control" %>
    <%= f.label :birth_date %>
  </div>
  
  <div class="mb-3 row">
    <%= f.label :profile_photo, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
    <%= f.file_field :profile_photo, class: "form-control" %>
    </div>
  </div>

  <%= f.submit class: "btn btn-primary mt-3 mb-3" %>
<% end %>

app/views/professional_profiles/edit.html.erb
<h1 class="display-5 mb-4"><%= "#{t('misc.edit')} #{ProfessionalProfile.model_name.human}" %></h1>

<%= render "shared/errors", resource: @professional_profile %>

<%= render 'form' %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>

app/views/professional_profiles/new.html.erb
<h1 class="display-5 mb-4"><%= "#{t('misc.create')} #{ProfessionalProfile.model_name.human}" %></h1>

<%= render "shared/errors", resource: @professional_profile %>

<%= render 'form' %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>

app/views/professional_profiles/show.html.erb
<h1 class="display-5 mb-4"><%= ProfessionalProfile.model_name.human %></h1>

<%= render "shared/errors", resource: @professional_profile %>

<% if @professional_profile.profile_photo.attached? %>
  <%= image_tag @professional_profile.profile_photo, size: "250x250", class: "rounded float-end" %>
<% end %>
<dl class="row">
  <p>
    <dt class="col-sm-3"><%= ProfessionalProfile.human_attribute_name(:full_name) %>:</dt>
    <dd class="col-sm-9"><%= @professional_profile.full_name %></dd>
  </p>
  <p>
    <dt class="col-sm-3"><%= ProfessionalProfile.human_attribute_name(:social_name) %>:</dt>
    <dd class="col-sm-9"><%= @professional_profile.social_name %></dd>
  </p>
  <p>
    <dt class="col-sm-3"><%= ProfessionalProfile.human_attribute_name(:description) %>:</dt>
    <dd class="col-sm-9"><%= @professional_profile.description %></dd>
  </p>
  <p>
    <dt class="col-sm-3"><%= ProfessionalProfile.human_attribute_name(:professional_qualification) %>:</dt>
    <dd class="col-sm-9"><%= @professional_profile.professional_qualification %></dd>
  </p>
  <p>
    <dt class="col-sm-3"><%= ProfessionalProfile.human_attribute_name(:professional_experience) %>:</dt>
    <dd class="col-sm-9"><%= @professional_profile.professional_experience %></dd>
  </p>
  <p>
    <dt class="col-sm-3"><%= KnowledgeField.model_name.human %>:</dt>
    <dd class="col-sm-9"><%= @professional_profile.knowledge_field.title %></dd>
  </p>
  <p>
    <dt class="col-sm-3"><%= ProfessionalProfile.human_attribute_name(:birth_date) %>:</dt>
    <dd class="col-sm-9"><%= l @professional_profile.birth_date %></dd>
  </p>
  <% if @professional_profile.user.average_score_received? > 0 %>
    <p>
      <dt class="col-sm-3"><%= t('misc.average_score') %>:</dt>
      <dd class="col-sm-9"><%= @professional_profile.user.average_score_received?.round(2) %></dd>
    </p>
  <% end %>
</dl>

<div>
  <div class="btn-group mt-1 mb-3" role="group" aria-label="Buttons related to the project">
    <%= link_to t('links.go_to_feedbacks'), received_feedbacks_path(@professional_profile.user), class: "btn btn-primary mt-3 mb-3" %>
    <% if @professional_profile.creator?(current_user) %>
      <%= link_to t('links.edit'), edit_professional_profile_path(@professional_profile), class: "btn btn-outline-primary mt-3 mb-3" %>
    <% end %>
  </div>
</div>

<% if @projects.present? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Project.human_attribute_name(:title) %></th>
        <th><%= Project.human_attribute_name(:description) %></th>
        <th><%= Project.human_attribute_name(:attendance_type) %></th>
        <th><%= Project.human_attribute_name(:status) %></th>
        <th><%= Feedback.human_attribute_name(:score) %></th>
      </tr>
    </thead>
    <tbody>
    <% @projects.each do |pr| %>
      <tr project-id="<%= pr.id %>">
        <td class="title"><%= link_to pr.title, project_path(pr) %></td>
        <td class="description"><%= pr.description %></td>
        <td class="attendance-type"><%= t(pr.attendance_type) %></td>
        <td class="status-type"><%= t(pr.status) %></td>
        <td class="score"><%= pr.score %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>