config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  root to: 'home#index'

  resources :projects, only: %i[index new create show edit update] do
    resources :project_proposals, only: %i[index update new create show] # shallow nesting breaks form_with on project show page
    post 'close', on: :member
    post 'finish', on: :member
    get 'my_projects', on: :collection
  end

  resources :project_proposals, only: %i[edit update destroy] do
    post 'approve', on: :member
    get 'cancel', on: :member
    get 'rate', on: :member
    get 'reject', on: :member
  end

  resources :professional_profiles, only: %i[new create edit update show]

  resources :feedbacks, only: %i[new create show] do
    get 'received/:user_id', on: :collection, to: 'feedbacks#feedbacks_received', as: :received
  end

  resources :knowledge_fields, only: %i[index new create]

  scope '/admin' do
    get 'manage_records', to: 'admin#manage_records'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :feedbacks, only: %i[index show]
      resources :knowledge_fields, only: %i[index show]
      resources :professional_profiles, only: %i[index show]
      resources :projects, only: %i[index show]
      resources :project_proposals, only: %i[index show]
      resources :users, only: %i[index show]
      get 'managers', to: 'users#managers'
      get 'professionals', to: 'users#professionals'
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  mount Coverband::Reporters::Web.new, at: '/coverage'
  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/models/knowledge_field.rb
class KnowledgeField < ApplicationRecord
  has_many :professional_profiles

  validates :title, presence: true
  validates :title, uniqueness: { case_sensitive: false }
end

app/controllers/api/v1/knowledge_fields_controller.rb
class Api::V1::KnowledgeFieldsController < Api::V1::ApiController
  deserializable_resource :knowledge_field

  def index
    @knowledge_fields = KnowledgeField.all

    return render_not_found if @knowledge_fields.nil?

    render jsonapi: @knowledge_fields, include: [:professional_profiles],
           fields: { professional_profile: [:social_name] },
           status: :ok
  end

  def show
    @knowledge_field = KnowledgeField.find(params[:id])

    render status: :ok,
           json: @knowledge_field.as_json(include: { professional_profiles: { only: %i[id social_name
                                                                                       user_id] } })
    # render status: :ok, json: @knowledge_field
  end
end

app/controllers/knowledge_fields_controller.rb
class KnowledgeFieldsController < ApplicationController
  before_action :require_admin_login

  def index
    @knowledge_fields = KnowledgeField.all
  end

  def new
    @knowledge_field = KnowledgeField.new
  end

  def create
    @knowledge_field = KnowledgeField.new(knowledge_field_params)

    if @knowledge_field.save
      redirect_to knowledge_fields_path, success: 'Área de Conhecimento cadastrada com sucesso!'
    else
      render :new
    end
  end

  private

  def knowledge_field_params
    params.require(:knowledge_field).permit(:title)
  end
end

app/views/knowledge_fields/_form.html.erb
<%= render "shared/errors", resource: @knowledge_field %>

<%= form_with model: @knowledge_field do |f| %>
  <div class="form-floating mb-3">
    <%= f.text_field :title, placeholder: :title, class: "form-control" %>
    <%= f.label :title %>

  <%= f.submit class: "btn btn-primary mt-3 mb-3" %>
<% end %>

app/views/knowledge_fields/index.html.erb
<h1 class="display-3"><%= KnowledgeField.model_name.human(count: 2) %></h1>

<%= render "shared/errors", resource: @knowledge_fields %>

<table class="table">
  <thead>
    <tr>
      <th><%= KnowledgeField.human_attribute_name(:title) %></th>
    </tr>
  </thead>
  <tbody>
  <% @knowledge_fields.each do |kf| %>
    <tr project-id="<%= kf.id %>">
      <td class="title"><%= kf.title %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= link_to t('links.new'), new_knowledge_field_path, class: "btn btn-primary mt-1 mb-1" %>
</div>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>

app/views/knowledge_fields/new.html.erb
<h1 class="display-5 mb-4">Cadastro de <%= KnowledgeField.model_name.human(count: 2) %></h1>

<%= render "shared/errors", resource: @knowledge_fields %>

<%= render 'form' %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>