config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  root to: 'home#index'

  resources :projects, only: %i[index new create show edit update] do
    resources :project_proposals, only: %i[index update new create show] # shallow nesting breaks form_with on project show page
    post 'close', on: :member
    post 'finish', on: :member
    get 'my_projects', on: :collection
  end

  resources :project_proposals, only: %i[edit update destroy] do
    post 'approve', on: :member
    get 'cancel', on: :member
    get 'rate', on: :member
    get 'reject', on: :member
  end

  resources :professional_profiles, only: %i[new create edit update show]

  resources :feedbacks, only: %i[new create show] do
    get 'received/:user_id', on: :collection, to: 'feedbacks#feedbacks_received', as: :received
  end

  resources :knowledge_fields, only: %i[index new create]

  scope '/admin' do
    get 'manage_records', to: 'admin#manage_records'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :feedbacks, only: %i[index show]
      resources :knowledge_fields, only: %i[index show]
      resources :professional_profiles, only: %i[index show]
      resources :projects, only: %i[index show]
      resources :project_proposals, only: %i[index show]
      resources :users, only: %i[index show]
      get 'managers', to: 'users#managers'
      get 'professionals', to: 'users#professionals'
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  mount Coverband::Reporters::Web.new, at: '/coverage'
  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_proposals

  enum status: { open: 10, closed: 20, finished: 30 },
       attendance_type: { mixed_attendance: 10, remote_attendance: 20, presential_attendance: 30 }

  validates :title, :description, :skills, :max_hourly_rate, :open_until, :attendance_type, presence: true

  validates :max_hourly_rate, numericality: { greater_than: 0 }

  validate :open_until_cannot_be_in_the_past
  validate :open_until_must_be_within_limit

  def closed!
    return super if open?

    errors.add(:status, 'do projeto não permite essa alteração')
  end

  def finished!
    return super if closed?

    errors.add(:status, 'do projeto não permite essa alteração')
  end

  def creator?(user_param)
    user == user_param
  end

  def currently_open?
    open? && open_until >= Date.current
  end

  def feedback_from_professional(professional)
    Feedback.joins(:project_proposal).find_by(feedback_creator: professional, project_proposal: { project: self })
  end

  def self.search(search_term)
    search_term = "%#{search_term}%"
    Project.where('title LIKE :title OR description LIKE :description', title: search_term, description: search_term)
  end

  private

  def open_until_cannot_be_in_the_past
    return unless changes.key?(:open_until)

    errors.add(:open_until, 'não pode estar no passado') unless open_until && open_until >= Date.current
  end

  def open_until_must_be_within_limit
    return unless changes.key?(:open_until)

    errors.add(:open_until, 'não pode passar de um ano') unless open_until && open_until <= 1.year.from_now
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::ApiController
  def index
    @projects = Project.all

    return render_not_found if @projects.nil?

    projects = @projects

    render json: projects, status: :ok
    # render json: @projects, status: :ok
    # render status: :ok, json: ProjectSerializer.new(@projects).serializable_hash
  end

  def show
    @project = Project.find(params[:id])

    return render status: :ok, json: @project.as_json if @project.id == 1
    return render :show, status: :ok if @project.id == 2

    render status: :ok, json: @project.as_json(only: %i[title status description])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :require_user_login, except: %i[index show my_projects]
  before_action :professional_must_fill_profile
  before_action :set_project, only: %i[show edit update close finish]

  def new
    redirect_to projects_path, alert: 'Criação de projetos desabilitada' unless Flipper.enabled?(:allow_creating_projects)
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to @project, success: 'Projeto cadastrado com sucesso!'
    else
      render :new
    end
  end

  def index
    @projects = Project.search(params[:query]) if params[:query] && params[:commit] == I18n.t('buttons.search')
    @projects ||= Project.all

    @projects = @projects.where(status: :open) unless current_user.admin?
  end

  def my_projects
    @projects = Project.search(params[:query]) if params[:query] && params[:commit] == I18n.t('buttons.search')
    @projects ||= Project.all

    @projects = if current_user.professional?
                  @projects.joins(:project_proposals).where(
                    status: :open, project_proposals: { user: current_user }
                  ).or(
                    @projects.joins(:project_proposals).where(
                      project_proposals: { user: current_user, status: %i[approved rated] }
                    )
                  )
                else
                  @projects.where(user: current_user)
                end
  end

  def show
    if current_user.professional? || current_user.admin?
      @project_proposal = ProjectProposal.find_by(project: @project, user: current_user) || ProjectProposal.new
      @feedback = @project.feedback_from_professional(current_user)
    end

    if @project.creator?(current_user)
      @project_proposals = ProjectProposal.where(project: @project)

      if @project_proposals && !@project.open?
        @project_proposals = @project_proposals.where(
          status: %i[approved rated]
        )
      end

      if @project.finished?
        from_user = Feedback.feedback_sources[:from_user].to_s

        @project_proposals = @project_proposals.joins(
          'LEFT JOIN feedbacks ON feedbacks.project_proposal_id = project_proposals.id AND feedbacks.feedback_source = ' + from_user
        ).select('project_proposals.*, feedbacks.id AS feedback_id').uniq
      end
    elsif !@project.open? && (@project_proposal.approved? || @project_proposal.rated?)
      @project_proposals = ProjectProposal.where(project: @project, status: %i[approved rated])
    end
  end

  def edit
    redirect_to @project, alert: 'Somente o autor do projeto pode editá-lo' unless @project.creator?(current_user)
  end

  def update
    if @project.update(project_params)
      redirect_to @project, success: 'Projeto atualizado com sucesso!'
    else
      render :edit
    end
  end

  def close
    unless @project.open?
      return redirect_to @project,
                         alert: 'Só é possível fechar projetos em aberto'
    end

    @project.closed!
    redirect_to @project, success: 'Projeto fechado com sucesso!'
  end

  def finish
    unless @project.closed?
      return redirect_to @project,
                         alert: 'Só é possível finalizar projetos fechados'
    end

    @project.finished!
    redirect_to @project, success: 'Projeto finalizado com sucesso!'
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :skills, :max_hourly_rate, :open_until, :attendance_type)
  end

  def require_user_login
    return if current_user&.user? || current_user&.admin?

    sign_out current_user
    redirect_to new_user_session_path, notice: 'Acesso restrito a usuários autenticados.'
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<%= render "shared/errors", resource: @project %>

<%= form_with model: @project do |f| %>
  <div class="form-floating mb-3">
    <%= f.text_field :title, placeholder: :title, class: "form-control" %>
    <%= f.label :title %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :description, placeholder: :description, class: "form-control" %>
    <%= f.label :description %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :skills, placeholder: :skills, class: "form-control" %>
    <%= f.label :skills %>
  </div>
  <div class="form-floating mb-3">
    <%= f.number_field :max_hourly_rate, placeholder: :max_hourly_rate, step: 0.5, class: "form-control" %>
    <%= f.label :max_hourly_rate %>
  </div>
  <div class="form-floating mb-3">
    <%= f.date_field :open_until, placeholder: :open_until, class: "form-control" %>
    <%= f.label :open_until %>
  </div>

  <div class="field">
    <%= f.label :attendance_type %><br />
    <p>
      <%= f.radio_button :attendance_type, "mixed_attendance" %>
      <%= f.label :attendance_type_mixed_attendance, t('mixed_attendance') %>
    </p>
    <p>
      <%= f.radio_button :attendance_type, "presential_attendance" %>
      <%= f.label :attendance_type_presential_attendance, t('presential_attendance') %>
    </p>
    <p>
      <%= f.radio_button :attendance_type, "remote_attendance" %>
      <%= f.label :attendance_type_remote_attendance, t('remote_attendance') %>
    </p>
  </div>

  <%= f.submit class: "btn btn-primary mt-3 mb-3" %>
<% end %>

app/views/projects/_professional.html.erb
<% if @project.finished? && (@project_proposal.approved? || @project_proposal.rated?) %>
  <div class="btn-group mt-1 mb-3" role="group" aria-label="Buttons related to the project">
    <% if @feedback %>
      <%= link_to t('links.go_to_feedback'), feedback_path(@feedback), class: "btn btn-primary" %>
    <% else %>
      <%= link_to t('links.rate_project'), new_feedback_path(project_proposal_id: @project_proposal), class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

<% if @project_proposal.new_record? && @project.currently_open? %>
  <div class="display-6 mb-3"><%= current_user.professional_profile.social_name %>, envie sua proposta para esse projeto preenchendo os campos abaixo:</div>
<% else %>
  <div class="display-6 mb-3"><%= current_user.professional_profile.social_name %>, você enviou a seguinte proposta para esse projeto:</div>
<% end %>

<% disable_field = !@project.currently_open? %>

<%= form_with model: [@project, @project_proposal] do |f| %>
  <div class="form-floating mb-3">
    <%= f.text_field :reason, placeholder: :reason, disabled: disable_field, class: "form-control" %>
    <%= f.label :reason %>
  </div>
  <div class="form-floating mb-3">
    <%= f.number_field :hourly_rate, placeholder: :hourly_rate, disabled: disable_field, class: "form-control" %>
    <%= f.label :hourly_rate %>
  </div>
  <div class="form-floating mb-3">
    <%= f.number_field :weekly_hours, placeholder: :weekly_hours, readonly: disable_field, class: "form-control" %>
    <%= f.label :weekly_hours %>
  </div>
  <div class="form-floating mb-3">
    <%= f.date_field :deadline, placeholder: :deadline, disabled: disable_field, class: "form-control" %>
    <%= f.label :deadline %>
  </div>
  <% unless @project_proposal.new_record? %>
    <div class="row mb-3">
      <div class="col-sm-2 col-form-label">
        <%= ProjectProposal.human_attribute_name(:status) %>:
      </div>
      <div class="col-sm-2 col-form-label">
        <%= t(@project_proposal.status) %>
      </div>
      <div class="col-sm-2 col-form-label">
        (<%= ProjectProposal.human_attribute_name(:status_date) %>:
      </div>
      <div class="col-sm-6 col-form-label">
        <%= l(@project_proposal.status_date.in_time_zone('Brasilia'), format: :short) %>)
      </div>
    </div>
  <% end %>
  <% if @project_proposal.status_reason.present? %>
    <div class="row mb-3">
      <div class="col-sm-2 col-form-label">
        <%= ProjectProposal.human_attribute_name(:status_reason) %>:
      </div>
      <div class="col-sm-8 col-form-label">
        <%= @project_proposal.status_reason %>
      </div>
    </div>
  <% end %>

  <% if @project.currently_open? %>
    <%= f.submit class: "btn btn-primary mt-3 mb-3" %>
  <% end %>
<% end %>

<% if @project_proposal.can_be_canceled? && !@project_proposal.new_record? && !@project.finished? %>
  <% if @project_proposal.approved? %>
    <%= link_to t('misc.cancel_param', param: ProjectProposal.model_name.human), cancel_project_proposal_path(@project_proposal, status_change: 'cancel'), class: "btn btn-outline-danger mt-3 mb-3" %>
  <% else %>
    <%= button_to t('misc.cancel_param', param: ProjectProposal.model_name.human), project_proposal_path(@project_proposal), data: { confirm: t('messages.are_you_sure?') },
        method: :delete, class: "btn btn-outline-danger mt-3 mb-3" %>
  <% end %>
<% end %>

<% if !@project.open? && (@project_proposal.approved? || @project_proposal.rated?) %>
  <div class="display-6 mb-3">Time do projeto:</div>
  <table class="table">
    <thead>
      <tr>
        <th><%= ProfessionalProfile.human_attribute_name(:social_name) %></th>
        <th><%= ProjectProposal.human_attribute_name(:reason) %></th>
        <th><%= ProjectProposal.human_attribute_name(:weekly_hours) %></th>
        <th><%= ProjectProposal.human_attribute_name(:deadline) %></th>
      </tr>
    </thead>
    <tbody>
      <% @project_proposals.each do |pp| %>
        <tr project-proposal-id="<%= pp.id %>">
          <td class="social-name"><%= link_to pp.user.professional_profile.social_name, pp.user.professional_profile %></td>
          <td class="reason"><%= pp.reason %></td>
          <td class="weekly-hours"><%= pp.weekly_hours %></td>
          <td class="deadline"><%= l pp.deadline %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/projects/_project_list.html.erb
<% if @projects.present? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Project.human_attribute_name(:title) %></th>
        <th><%= Project.human_attribute_name(:description) %></th>
        <th><%= Project.human_attribute_name(:max_hourly_rate) %></th>
        <th><%= Project.human_attribute_name(:open_until) %></th>
        <th><%= Project.human_attribute_name(:attendance_type) %></th>
        <th><%= Project.human_attribute_name(:status) %></th>
      </tr>
    </thead>
    <tbody>
    <% @projects.each do |pr| %>
      <tr project-id="<%= pr.id %>">
        <td class="title"><%= link_to pr.title, project_path(pr) %></td>
        <td class="description"><%= pr.description %></td>
        <td class="max-hourly-rate"><%= pr.max_hourly_rate %></td>
        <td class="open-until"><%= l pr.open_until %></td>
        <td class="attendance-type"><%= t(pr.attendance_type) %></td>
        <td class="status-type"><%= t(pr.status) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info" role="alert">
    <%= t('messages.no_projects_found') %>
  </div>
<% end %>

app/views/projects/_user.html.erb
<% if @project.creator?(current_user) %>
  <div class="btn-group mt-1 mb-3" role="group" aria-label="Buttons related to the project">
    <% if @project.open? %>
      <%= link_to t('links.edit'), edit_project_path(@project), class: "btn btn-primary" %>
      <%= link_to t('links.close'), close_project_path(@project), method: :post,
          data: { confirm: t('messages.are_you_sure?') }, class: "btn btn-outline-primary" %>
    <% elsif @project.closed? %>
      <%= link_to t('links.finish'), finish_project_path(@project), method: :post,
          data: { confirm: t('messages.are_you_sure?') }, class: "btn btn-outline-danger" %>
    <% end %>
  </div>
<% end %>

<% if @project_proposals.present? %>
  <div class="display-6 mb-3">Propostas enviadas:</div>
  <table class="table">
    <thead>
      <tr>
        <th><%= ProfessionalProfile.human_attribute_name(:social_name) %></th>
        <th><%= ProjectProposal.human_attribute_name(:reason) %></th>
        <th><%= ProjectProposal.human_attribute_name(:hourly_rate) %></th>
        <th><%= ProjectProposal.human_attribute_name(:weekly_hours) %></th>
        <th><%= ProjectProposal.human_attribute_name(:deadline) %></th>
        <% if @project.finished? %>
          <th></th>
        <% elsif @project.open? %>
          <th></th>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @project_proposals.each do |pp| %>
        <tr project-proposal-id="<%= pp.id %>">
          <td class="social-name"><%= link_to pp.user.professional_profile.social_name, pp.user.professional_profile %></td>
          <td class="reason"><%= pp.reason %></td>
          <td class="hourly-rate"><%= pp.hourly_rate %></td>
          <td class="weekly-hours"><%= pp.weekly_hours %></td>
          <td class="deadline"><%= l pp.deadline %></td>
          <% if @project.finished? %>
            <% if pp.rated? %>
              <td class="feedback-button"><%= link_to t('links.go_to_feedback'), feedback_path(pp.feedback_id),
                  id: pp.id, class: "btn btn-info btn-sm" %></td>
            <% else %>
              <td class="feedback-button"><%= link_to t('buttons.rate'), new_feedback_path(project_proposal_id: pp),
                  id: pp.id, class: "btn btn-outline-info btn-sm" %></td>
            <% end %>
          <% elsif @project.open? %>
            <% case %>
            <% when pp.pending? %>
              <td class="approve-button"><%= button_to 'Aprovar', approve_project_proposal_path(pp),
                  data: { confirm: t('messages.are_you_sure?') }, id: pp.id, class: "btn btn-outline-success btn-sm" %></td>
              <td class="reject-button"><%= link_to 'Rejeitar', reject_project_proposal_path(pp, status_change: 'reject'),
                  id: pp.id, class: "btn btn-outline-danger btn-sm" %></td>
            <% when pp.approved? %>
              <td class="approve-button"><%= button_to 'Aprovar', '#', id: pp.id, class: "btn btn-success disabled btn-sm" %></td>
              <td class="reject-button"><%= button_to 'Rejeitar', '#', id: pp.id, class: "btn btn-outline-danger disabled btn-sm" %></td>
            <% when pp.rejected? %>
              <td class="approve-button"><%= button_to 'Aprovar', '#', id: pp.id, class: "btn btn-outline-success disabled btn-sm" %></td>
              <td class="reject-button"><%= button_to 'Rejeitar', '#', id: pp.id, class: "btn btn-danger disabled btn-sm" %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/projects/edit.html.erb
<h1 class="display-5 mb-4"><%= "#{t('misc.edit')} #{Project.model_name.human}" %></h1>

<%= render "shared/errors", resource: @project %>

<%= render 'form' %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>

app/views/projects/index.html.erb
<h1 class="display-4 mb-4"><%= Project.model_name.human(count: 2) %></h1>

<%= render "shared/errors", resource: @projects %>

<table class="table">
  <thead>
    <tr>
      <th><%= Project.human_attribute_name(:title) %></th>
      <th><%= Project.human_attribute_name(:description) %></th>
      <th><%= Project.human_attribute_name(:max_hourly_rate) %></th>
      <th><%= Project.human_attribute_name(:open_until) %></th>
      <th><%= Project.human_attribute_name(:attendance_type) %></th>
      <th><%= Project.human_attribute_name(:status) %></th>
    </tr>
  </thead>
  <tbody>
  <% @projects.each do |pr| %>
    <tr project-id="<%= pr.id %>">
      <td class="title"><%= link_to pr.title, project_path(pr) %></td>
      <td class="description"><%= pr.description %></td>
      <td class="max-hourly-rate"><%= pr.max_hourly_rate %></td>
      <td class="open-until"><%= l pr.open_until %></td>
      <td class="attendance-type"><%= t(pr.attendance_type) %></td>
      <td class="status-type"><%= t(pr.status) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>

app/views/projects/my_projects.html.erb
<h1 class="display-4 mb-4"><%= t('messages.my_projects') %></h1>

<%= render "shared/errors", resource: @projects %>

<%= form_with url: my_projects_projects_path, method: :get do |f| %>
  <div class="col-6 mb-3">
    <div class="input-group">
      <%= f.text_field :query, placeholder: t('messages.search_by_title_or_description'), class: "form-control col-auto" %>
      <%= f.submit t('buttons.search'), class: "btn btn-primary col-auto" %>
    </div>
  </div>
<% end %>
<% if params[:query].present? %>
  <%= button_to t('buttons.clean_filters'), my_projects_projects_path, method: :get, class: "btn btn-outline-secondary mb-3" %>
<% end %>

<%= render 'project_list' %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>

app/views/projects/new.html.erb
<h1 class="display-5 mb-4"><%= "#{t('misc.create')} #{Project.model_name.human}" %></h1>

<%= render "shared/errors", resource: @project %>

<%= render 'form' %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>

app/views/projects/show.html.erb
<h1 class="display-3"><%= @project.title %></h1>

<%= render "shared/errors", resource: @project %>

<dl class="row">
    <%= tag.p do %>
      <%= tag.dt "#{Project.human_attribute_name(:description)}:", class: 'col-sm-3' %>
      <%= tag.dd @project.description, class: 'col-sm-9' %>
    <% end %>
    <p>
      <dt class="col-sm-3"><%= Project.human_attribute_name(:description) %>:</dt>
      <dd class="col-sm-9"><%= @project.description %></dd>
    </p>
    <p>
      <dt class="col-sm-3"><%= Project.human_attribute_name(:skills) %>:</dt>
      <dd class="col-sm-9"><%= @project.skills %></dd>
    </p>
    <p>
      <dt class="col-sm-3"><%= Project.human_attribute_name(:max_hourly_rate) %>:</dt>
      <dd class="col-sm-9"><%= number_to_currency(@project.max_hourly_rate) %></dd>
    </p>
    <p>
      <dt class="col-sm-3"><%= Project.human_attribute_name(:open_until) %>:</dt>
      <dd class="col-sm-9"><%= l @project.open_until %></dd>
    </p>
    <p>
      <dt class="col-sm-3"><%= Project.human_attribute_name(:attendance_type) %>:</dt>
      <dd class="col-sm-9"><%= t(@project.attendance_type) %></dd>
    </p>
    <p>
      <dt class="col-sm-3"><%= User.model_name.human %> responsável:</dt>
      <dd class="col-sm-9">
        <% average_score = @project.user.average_score_received?.round(2) %>
        <% if average_score > 0 %>
          <%= link_to "#{@project.user.email} (#{t('misc.average_score')}: #{average_score})", received_feedbacks_path(@project.user) %>
        <% else %>
          <%= @project.user.email %>
        <% end %>
      </dd>
    </p>
    <p>
      <dt class="col-sm-3"><%= Project.human_attribute_name(:status) %>:</dt>
      <dd class="col-sm-9"><%= t(@project.status) %></dd>
    </p>
</dl>

<% if current_user&.professional? %>
  <%= render 'professional' %>
<% end %>

<% if current_user&.user? || current_user&.admin? %>
  <%= render 'user' %>
<% end %>

<div>
  <%= link_to t('links.go_back'), :back, class: "btn btn-outline-primary mt-1 mb-1" %>
</div>