config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  root to: 'home#index'

  resources :projects, only: %i[index new create show edit update] do
    resources :project_proposals, only: %i[index update new create show] # shallow nesting breaks form_with on project show page
    post 'close', on: :member
    post 'finish', on: :member
    get 'my_projects', on: :collection
  end

  resources :project_proposals, only: %i[edit update destroy] do
    post 'approve', on: :member
    get 'cancel', on: :member
    get 'rate', on: :member
    get 'reject', on: :member
  end

  resources :professional_profiles, only: %i[new create edit update show]

  resources :feedbacks, only: %i[new create show] do
    get 'received/:user_id', on: :collection, to: 'feedbacks#feedbacks_received', as: :received
  end

  resources :knowledge_fields, only: %i[index new create]

  scope '/admin' do
    get 'manage_records', to: 'admin#manage_records'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :feedbacks, only: %i[index show]
      resources :knowledge_fields, only: %i[index show]
      resources :professional_profiles, only: %i[index show]
      resources :projects, only: %i[index show]
      resources :project_proposals, only: %i[index show]
      resources :users, only: %i[index show]
      get 'managers', to: 'users#managers'
      get 'professionals', to: 'users#professionals'
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  mount Coverband::Reporters::Web.new, at: '/coverage'
  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proseeker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container-fluid">
          <%= link_to 'ProSeeker', root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to 'Projetos', projects_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to 'Meus Projetos', my_projects_projects_path, class: "nav-link" %></li>
                <% if current_user.user? || current_user.admin? %>
                  <li class="nav-item"><%= link_to 'Cadastrar Novo Projeto', new_project_path, class: "nav-link" %></li>
                <% end %>

                <% if current_user.professional? %>
                  <li class="nav-item"><%= link_to 'Meu Perfil', current_user.professional_profile, class: "nav-link" %></li>
                <% end %>

                <% if current_user.admin? %>
                  <li class="nav-item"><%= link_to 'Gerenciar Cadastros', manage_records_path, class: "nav-link" %></li>
                <% end %>
                <li class="nav-item"><span class="nav-link">Logado como '<%= current_user.email %>' (<%= t(current_user.role) %>)</span></li>
                <li class="nav-item"><%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
              <% else %>
                <li class="nav-item"><%= link_to 'Entrar', new_user_session_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to 'Registrar', new_user_registration_path, class: "nav-link" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if success %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= success %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if notice %>
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if warning %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= warning %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>